blank_issues_enabled: true
contact_links:
  - name: ðŸ“º World of Zero on YouTube
    url: https://www.youtube.com/c/WorldofzeroDevelopment
    about: View Development on YouTube
  - name: ðŸŒŽ World of Zero
    url: https://www.worldofzero.com
    about: More About World of Zero
